export const LOADING_DETAIL = 'LOADING_DETAIL';
export const FETCH_DETAIL = 'FETCH_DETAIL';
export const LOAD_MOVIE_FAILED = 'LOAD_MOVIE_FAILED';

export const LOAD_GENRES = 'LOAD_GENRES';
export const LOADING_GENRES = 'LOADING_GENRES';

export const LOADING_MOVIES = 'LOADING_MOVIES';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_TRENDING_MOVIES = 'FETCH_TRENDING_MOVIES';
export const FETCH_KIDS_MOVIES = 'FETCH_KIDS_MOVIES';
export const FETCH_ADULTS_MOVIES = 'FETCH_ADULTS_MOVIES';
export const LOAD_GENRE_MOVIES = 'LOAD_GENRE_MOVIES';
export const LOAD_FAILED = 'LOAD_FAILED';
